### ISSUE TITLE
movies?

### ISSUE THREAD

**Issue by jrmullins** [neo4j-examples/movies-ruby-neo4j-core#1]
Is this application expecting a folder to be named movies and contain something? Would be helpful to explain this in the readme. Trying to set this up unsuccessfully.

**Comment by cheerfulstoic** [comment]
Shouldn't be, are you getting an error that says that it does?

You'll need to run the `:play movies` in Neo4j to load the data.  That would certainly be good for the `README`

**Comment by jrmullins** [comment]
Thanks, I finally got it working.

**Comment by jexp** [comment]
@cheerfulstoic can you please add it to the readme?
Perhaps we should also provide a simple load command like: 

http://jexp.github.io/graphgist/idx?f78df7b232d0faa171ff

I think I even have the CSV there: https://github.com/neo4j-contrib/developer-resources/blob/gh-pages/cypher/movies_actors.csv

**Comment by jexp** [comment]
I can add something to the example-project page which we should link back to anyway.

**Comment by cheerfulstoic** [comment]
Done, sorry for the delay!
